import Vue from 'nativescript-vue';
import Home from './components/Home.vue';

declare let __DEV__: boolean;

// Prints Vue logs when --env.production is *NOT* set while building
Vue.config.silent = !__DEV__;

Vue.registerElement(
  'DropDown',
  () => require('nativescript-drop-down/drop-down').DropDown
);

new Vue({
  render: (h) => h('frame', [h(Home)]),

  data: {
    products: [
      {
        id: '85',
        name: 'DELIVERY',
        cost: '1.2',
        price1000: null,
        price100: '0.18',
        price50: '0.10',
        unit: 's',
        type: '',
        category: 'Servicio',
        stock: '0',
        can_jar: '0',
        status: '1',
        has_details: '0',
        description: null,
        web: '0',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '124',
        name: '10 CARAMELOS DE COCO',
        cost: '0.6',
        price1000: '1.00',
        price100: '0.09',
        price50: '0.05',
        unit: 'u',
        type: null,
        category: 'Otros',
        stock: '0',
        can_jar: '0',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '115',
        name: '10 CARAMELOS DE JENGIBRE',
        cost: '0.6',
        price1000: '1.00',
        price100: '0.09',
        price50: '0.05',
        unit: 'u',
        type: null,
        category: 'Otros',
        stock: '0',
        can_jar: '0',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '64',
        name: 'ADOBO',
        cost: '3.41317144',
        price1000: '4.78',
        price100: '0.51',
        price50: '0.29',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '5000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '0',
        external_id: '194',
        newStock: '',
        jared: '',
      },
      {
        id: '49',
        name: 'AFRECHO',
        cost: '2.75091979',
        price1000: '3.85',
        price100: '0.41',
        price50: '0.23',
        unit: 'g',
        type: '',
        category: 'Cereales',
        stock: '5000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'AFRECHO1',
        newStock: '',
        jared: '',
      },
      {
        id: '117',
        name: 'AJINOMOTO',
        cost: '7.31309786',
        price1000: '10.24',
        price100: '1.10',
        price50: '0.62',
        unit: 'g',
        type: null,
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'AJINO1001',
        newStock: '',
        jared: '',
      },
      {
        id: '66',
        name: 'AJO MOLIDO CHINO',
        cost: '11.2866077',
        price1000: '15.80',
        price100: '1.69',
        price50: '0.96',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '10000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'AJOCHI',
        newStock: '',
        jared: '',
      },
      {
        id: '65',
        name: 'AJO. CEBOLLIN Y PEREJIL',
        cost: '6.50367917',
        price1000: '9.11',
        price100: '0.98',
        price50: '0.55',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'COND019',
        newStock: '',
        jared: '',
      },
      {
        id: '44',
        name: 'AJONJOLI',
        cost: '10',
        price1000: '15.00',
        price100: '1.50',
        price50: '0.80',
        unit: 'g',
        type: '',
        category: 'Cereales',
        stock: '7000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'AJONB',
        newStock: '',
        jared: '',
      },
      {
        id: '116',
        name: 'ALBAHACA',
        cost: '10.77',
        price1000: '15.08',
        price100: '1.62',
        price50: '0.92',
        unit: 'g',
        type: null,
        category: 'Infusiones',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '220',
        newStock: '',
        jared: '',
      },
      {
        id: '67',
        name: 'ALIÑO PREPARADO',
        cost: '4.59050772',
        price1000: '6.43',
        price100: '0.69',
        price50: '0.39',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '265',
        newStock: '',
        jared: '',
      },
      {
        id: '19',
        name: 'ALMENDRAS',
        cost: '15.8487858',
        price1000: '22.19',
        price100: '2.38',
        price50: '1.35',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'ALMEXC',
        newStock: '',
        jared: '',
      },
      {
        id: '48',
        name: 'ALPISTE',
        cost: '5.32634289',
        price1000: '7.46',
        price100: '0.80',
        price50: '0.45',
        unit: 'g',
        type: '',
        category: 'Cereales',
        stock: '10000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'ALP',
        newStock: '',
        jared: '',
      },
      {
        id: '68',
        name: 'ANIS DULCE',
        cost: '17',
        price1000: '23.00',
        price100: '2.60',
        price50: '1.40',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'COND-ANIS1001',
        newStock: '',
        jared: '',
      },
      {
        id: '63',
        name: 'AREQUIPE S/A (ESTEVIA)',
        cost: '1.2',
        price1000: '4.18',
        price100: '0.18',
        price50: '0.10',
        unit: 'u',
        type: '',
        category: 'Otros',
        stock: '0',
        can_jar: '0',
        status: '1',
        has_details: '0',
        description: null,
        web: '0',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '108',
        name: 'AVELLANAS',
        cost: '21.1428571',
        price1000: '29.50',
        price100: '3.20',
        price50: '1.90',
        unit: 'g',
        type: null,
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'AVECONCH',
        newStock: '',
        jared: '',
      },
      {
        id: '41',
        name: 'AVENA EN HOJUELAS',
        cost: '3.33958793',
        price1000: '4.68',
        price100: '0.50',
        price50: '0.28',
        unit: 'g',
        type: '',
        category: 'Cereales',
        stock: '5000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'AVENAALM',
        newStock: '',
        jared: '',
      },
      {
        id: '99',
        name: 'CANELA EN POLVO',
        cost: '21.7354672',
        price1000: '30.43',
        price100: '3.26',
        price50: '1.85',
        unit: 'g',
        type: null,
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '080',
        newStock: '',
        jared: '',
      },
      {
        id: '69',
        name: 'CARMENCITA',
        cost: '6.65084621',
        price1000: '9.31',
        price100: '1.00',
        price50: '0.57',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'CARMEN',
        newStock: '',
        jared: '',
      },
      {
        id: '42',
        name: 'CEBADA',
        cost: '5.54709345',
        price1000: '7.77',
        price100: '0.83',
        price50: '0.47',
        unit: 'g',
        type: '',
        category: 'Cereales',
        stock: '5000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '087',
        newStock: '',
        jared: '',
      },
      {
        id: '70',
        name: 'CEBOLLA GRANULADA',
        cost: '11.0890410',
        price1000: '15.52',
        price100: '1.66',
        price50: '0.94',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'COND-CEBOLL-1001',
        newStock: '',
        jared: '',
      },
      {
        id: '59',
        name: 'CHIA',
        cost: '11.45',
        price1000: '16.03',
        price100: '1.72',
        price50: '0.97',
        unit: 'g',
        type: '',
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '71',
        name: 'CILANTRO ENTERO',
        cost: '10.9473311',
        price1000: '15.33',
        price100: '1.64',
        price50: '0.93',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '081',
        newStock: '',
        jared: '',
      },
      {
        id: '57',
        name: 'CIRUELAS PASAS',
        cost: '11.8920642',
        price1000: '16.65',
        price100: '1.78',
        price50: '1.01',
        unit: 'g',
        type: '',
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'CIRU1002',
        newStock: '',
        jared: '',
      },
      {
        id: '107',
        name: 'COMINO ENTERO',
        cost: '11.45',
        price1000: '16.03',
        price100: '1.72',
        price50: '0.97',
        unit: 'g',
        type: null,
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '',
        newStock: '',
        jared: '',
      },
      {
        id: '72',
        name: 'COMINO MOLIDO',
        cost: '12.8095238',
        price1000: '17.93',
        price100: '1.92',
        price50: '1.09',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'COMINO1',
        newStock: '',
        jared: '',
      },
      {
        id: '73',
        name: 'CURCUMA',
        cost: '10.5507726',
        price1000: '14.77',
        price100: '1.58',
        price50: '0.90',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'ADOBO',
        newStock: '',
        jared: '',
      },
      {
        id: '74',
        name: 'CURRY',
        cost: '8.84',
        price1000: '12.38',
        price100: '1.33',
        price50: '0.75',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'CURRY',
        newStock: '',
        jared: '',
      },
      {
        id: '60',
        name: 'ESTEVIA',
        cost: '10.77',
        price1000: '19.38',
        price100: '1.62',
        price50: '0.92',
        unit: 'g',
        type: '',
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '33',
        name: 'FLOR DE JAMAICA',
        cost: '11.2866077',
        price1000: '15.80',
        price100: '1.69',
        price50: '0.96',
        unit: 'g',
        type: '',
        category: 'Infusiones',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '304',
        newStock: '',
        jared: '',
      },
      {
        id: '95',
        name: 'FRASCO DE VIDRIO',
        cost: '1.70377834',
        price1000: '2.39',
        price100: '0.26',
        price50: '0.14',
        unit: 'u',
        type: null,
        category: 'Otros',
        stock: '0',
        can_jar: '0',
        status: '1',
        has_details: '0',
        description: null,
        web: '0',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '52',
        name: 'FRUTAS CONFITADAS',
        cost: '5.07142857',
        price1000: '7.10',
        price100: '0.76',
        price50: '0.43',
        unit: 'g',
        type: '',
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '0',
        external_id: '420',
        newStock: '',
        jared: '',
      },
      {
        id: '50',
        name: 'GIRASOL',
        cost: '4.95842531',
        price1000: '6.94',
        price100: '0.74',
        price50: '0.42',
        unit: 'g',
        type: '',
        category: 'Cereales',
        stock: '5000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'GIRASOL2',
        newStock: '',
        jared: '',
      },
      {
        id: '106',
        name: 'GOMITAS ARITOS',
        cost: '8.19',
        price1000: '11.47',
        price100: '1.23',
        price50: '0.70',
        unit: 'g',
        type: null,
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '393',
        newStock: '',
        jared: '',
      },
      {
        id: '111',
        name: 'GOMITAS BANANAS',
        cost: '8.19',
        price1000: '11.47',
        price100: '1.23',
        price50: '0.70',
        unit: 'g',
        type: null,
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '393',
        newStock: '',
        jared: '',
      },
      {
        id: '54',
        name: 'GOMITAS IMPORTADAS',
        cost: '8.19',
        price1000: '11.47',
        price100: '1.23',
        price50: '0.70',
        unit: 'g',
        type: '',
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '0',
        external_id: '393',
        newStock: '',
        jared: '',
      },
      {
        id: '114',
        name: 'GOMITAS MORAS AZULES',
        cost: '8.19',
        price1000: '11.47',
        price100: '1.23',
        price50: '0.70',
        unit: 'g',
        type: null,
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '393',
        newStock: '',
        jared: '',
      },
      {
        id: '113',
        name: 'GOMITAS MORAS NARANJAS',
        cost: '8.19',
        price1000: '11.47',
        price100: '1.23',
        price50: '0.70',
        unit: 'g',
        type: null,
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '393',
        newStock: '',
        jared: '',
      },
      {
        id: '112',
        name: 'GOMITAS MULTICOLOR',
        cost: '8.19',
        price1000: '11.47',
        price100: '1.23',
        price50: '0.70',
        unit: 'g',
        type: null,
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '393',
        newStock: '',
        jared: '',
      },
      {
        id: '105',
        name: 'GOMITAS OSITOS',
        cost: '8.19',
        price1000: '11.47',
        price100: '1.23',
        price50: '0.70',
        unit: 'g',
        type: null,
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '393',
        newStock: '',
        jared: '',
      },
      {
        id: '120',
        name: 'GRANOLA CHOCONOLA',
        cost: '10.0025980',
        price1000: '14.00',
        price100: '1.50',
        price50: '0.85',
        unit: 'g',
        type: null,
        category: 'Cereales',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'GRAMAIZ',
        newStock: '',
        jared: '',
      },
      {
        id: '43',
        name: 'GRANOLA DE AVENA',
        cost: '8.86891828',
        price1000: '12.42',
        price100: '1.33',
        price50: '0.75',
        unit: 'g',
        type: '',
        category: 'Cereales',
        stock: '5000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'GRAAVENA',
        newStock: '',
        jared: '',
      },
      {
        id: '40',
        name: 'GRANOLA DE MIEL',
        cost: '9.00551876',
        price1000: '12.61',
        price100: '1.35',
        price50: '0.77',
        unit: 'g',
        type: '',
        category: 'Cereales',
        stock: '5000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '03001',
        newStock: '',
        jared: '',
      },
      {
        id: '103',
        name: 'HIERBABUENA SECA',
        cost: '11.24',
        price1000: '15.70',
        price100: '1.68',
        price50: '0.95',
        unit: 'g',
        type: null,
        category: 'Infusiones',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'TOMA1300',
        newStock: '',
        jared: '',
      },
      {
        id: '109',
        name: 'JENGIBRE EN POLVO',
        cost: '10.55',
        price1000: '14.77',
        price100: '1.58',
        price50: '0.84',
        unit: 'g',
        type: null,
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'ESPECIE-JENGIBRE.',
        newStock: '',
        jared: '',
      },
      {
        id: '58',
        name: 'LAUREL',
        cost: '9.66777041',
        price1000: '13.53',
        price100: '1.45',
        price50: '0.82',
        unit: 'g',
        type: '',
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '118',
        newStock: '',
        jared: '',
      },
      {
        id: '61',
        name: 'LECHE DE ALMENDRAS S/A',
        cost: '3.21511335',
        price1000: '4.50',
        price100: '0.48',
        price50: '0.27',
        unit: 'u',
        type: '',
        category: 'Otros',
        stock: '0',
        can_jar: '0',
        status: '1',
        has_details: '0',
        description: null,
        web: '0',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '62',
        name: 'LECHE DE COCO S/A',
        cost: '3.21511335',
        price1000: '4.50',
        price100: '0.48',
        price50: '0.27',
        unit: 'u',
        type: '',
        category: 'Otros',
        stock: '0',
        can_jar: '0',
        status: '1',
        has_details: '0',
        description: null,
        web: '0',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '51',
        name: 'LINAZA',
        cost: '5.84577231',
        price1000: '8.18',
        price100: '0.88',
        price50: '0.50',
        unit: 'g',
        type: '',
        category: 'Cereales',
        stock: '5000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'LINAZA2',
        newStock: '',
        jared: '',
      },
      {
        id: '121',
        name: 'MALAGUETA',
        cost: '22',
        price1000: '30.80',
        price100: '3.30',
        price50: '1.87',
        unit: 'g',
        type: null,
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '079',
        newStock: '',
        jared: '',
      },
      {
        id: '20',
        name: 'MANI CON AJONJOLI',
        cost: '5.62067696',
        price1000: '8.00',
        price100: '0.80',
        price50: '0.40',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '045',
        newStock: '',
        jared: '',
      },
      {
        id: '21',
        name: 'MANI CON AVENA',
        cost: '5.67',
        price1000: '9.00',
        price100: '0.95',
        price50: '0.50',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '0092',
        newStock: '',
        jared: '',
      },
      {
        id: '22',
        name: 'MANI CON COCO',
        cost: '6.85714285',
        price1000: '10.00',
        price100: '1.10',
        price50: '0.60',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '080T',
        newStock: '',
        jared: '',
      },
      {
        id: '24',
        name: 'MANI GARRAPIÑADO',
        cost: '5.62067696',
        price1000: '8.00',
        price100: '0.80',
        price50: '0.40',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '268',
        newStock: '',
        jared: '',
      },
      {
        id: '110',
        name: 'MANI JAPONÉS MIXTO',
        cost: '9.5',
        price1000: '13.30',
        price100: '1.42',
        price50: '0.80',
        unit: 'g',
        type: null,
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '0035',
        newStock: '',
        jared: '',
      },
      {
        id: '25',
        name: 'MANI MIXTO',
        cost: '6',
        price1000: '9.00',
        price100: '0.95',
        price50: '0.50',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '1',
        description: null,
        web: '1',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '26',
        name: 'MANI MIXTO ESPECIAL',
        cost: '9',
        price1000: '14.00',
        price100: '1.50',
        price50: '0.80',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '1',
        description: null,
        web: '1',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '27',
        name: 'MANI MIXTO PREMIUM',
        cost: '11',
        price1000: '17.00',
        price100: '1.80',
        price50: '0.95',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '1',
        description: null,
        web: '1',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '29',
        name: 'MANI TOSTADO C/S',
        cost: '6.20934510',
        price1000: '9.00',
        price100: '0.95',
        price50: '0.50',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '596',
        newStock: '',
        jared: '',
      },
      {
        id: '28',
        name: 'MANI TOSTADO S/S',
        cost: '6.20934510',
        price1000: '9.00',
        price100: '0.95',
        price50: '0.50',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'MSS',
        newStock: '',
        jared: '',
      },
      {
        id: '100',
        name: 'MANZANILLA',
        cost: '21.7',
        price1000: '30.38',
        price100: '3.26',
        price50: '1.84',
        unit: 'g',
        type: null,
        category: 'Infusiones',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'MANZANI',
        newStock: '',
        jared: '',
      },
      {
        id: '38',
        name: 'MENTA',
        cost: '10.43',
        price1000: '14.60',
        price100: '1.56',
        price50: '0.89',
        unit: 'g',
        type: '',
        category: 'Infusiones',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '285',
        newStock: '',
        jared: '',
      },
      {
        id: '30',
        name: 'MEREY TOSTADO S/S',
        cost: '16',
        price1000: '24.00',
        price100: '2.50',
        price50: '1.40',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'MEREXC',
        newStock: '',
        jared: '',
      },
      {
        id: '56',
        name: 'MIEL PURA 600G',
        cost: '4.85239295',
        price1000: '6.79',
        price100: '0.73',
        price50: '0.41',
        unit: 'u',
        type: '',
        category: 'Otros',
        stock: '10',
        can_jar: '0',
        status: '1',
        has_details: '0',
        description: null,
        web: '0',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '31',
        name: 'NUECES PELADAS',
        cost: '16.3809523',
        price1000: '24.00',
        price100: '2.50',
        price50: '1.40',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '261',
        newStock: '',
        jared: '',
      },
      {
        id: '119',
        name: 'NUEZ MOSCADA',
        cost: '29.3145695',
        price1000: '41.04',
        price100: '4.40',
        price50: '2.49',
        unit: 'g',
        type: null,
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '655',
        newStock: '',
        jared: '',
      },
      {
        id: '75',
        name: 'ONOTO EN GRANO',
        cost: '6.69603212',
        price1000: '9.37',
        price100: '1.00',
        price50: '0.57',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'ONOTO-001',
        newStock: '',
        jared: '',
      },
      {
        id: '76',
        name: 'OREGANO ENTERO',
        cost: '3.56033848',
        price1000: '4.98',
        price100: '0.53',
        price50: '0.30',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '192',
        newStock: '',
        jared: '',
      },
      {
        id: '77',
        name: 'OREGANO MOLIDO',
        cost: '4.17857142',
        price1000: '5.85',
        price100: '0.63',
        price50: '0.36',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '191',
        newStock: '',
        jared: '',
      },
      {
        id: '78',
        name: 'PEREJIL DEHIDRATADO',
        cost: '12.29',
        price1000: '17.21',
        price100: '1.84',
        price50: '1.04',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'PEREJIL',
        newStock: '',
        jared: '',
      },
      {
        id: '79',
        name: 'PIMENTON DULCE (PAPRIKA)',
        cost: '10.4285714',
        price1000: '14.60',
        price100: '1.56',
        price50: '0.89',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '593',
        newStock: '',
        jared: '',
      },
      {
        id: '80',
        name: 'PIMENTON PICANTE (PAPRIKA)',
        cost: '10.4749645',
        price1000: '14.66',
        price100: '1.57',
        price50: '0.89',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '197',
        newStock: '',
        jared: '',
      },
      {
        id: '118',
        name: 'PIMIENTA NEGRA ENTERA',
        cost: '16.1431199',
        price1000: '22.60',
        price100: '2.42',
        price50: '1.37',
        unit: 'g',
        type: null,
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '95',
        newStock: '',
        jared: '',
      },
      {
        id: '81',
        name: 'PIMIENTA NEGRA MOLIDA',
        cost: '16.5846210',
        price1000: '23.22',
        price100: '2.49',
        price50: '1.41',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'PIMI',
        newStock: '',
        jared: '',
      },
      {
        id: '104',
        name: 'PIMIENTA NEGRA SEGUNDA',
        cost: '5.25275938',
        price1000: '7.35',
        price100: '0.79',
        price50: '0.45',
        unit: 'g',
        type: null,
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '0',
        external_id: '238',
        newStock: '',
        jared: '',
      },
      {
        id: '32',
        name: 'PISTACHO C/S',
        cost: '30.8598233',
        price1000: '43.20',
        price100: '4.63',
        price50: '2.62',
        unit: 'g',
        type: '',
        category: 'Manicería',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'PISTAC',
        newStock: '',
        jared: '',
      },
      {
        id: '82',
        name: 'POLVO PARA HORNEAR',
        cost: '7.63',
        price1000: '10.68',
        price100: '1.14',
        price50: '0.65',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'VAINIPOLVO',
        newStock: '',
        jared: '',
      },
      {
        id: '46',
        name: 'QUINOA',
        cost: '7.54',
        price1000: '10.56',
        price100: '1.13',
        price50: '0.64',
        unit: 'g',
        type: '',
        category: 'Cereales',
        stock: '5000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '064',
        newStock: '',
        jared: '',
      },
      {
        id: '37',
        name: 'ROMERO',
        cost: '10.71',
        price1000: '14.99',
        price100: '1.61',
        price50: '0.91',
        unit: 'g',
        type: '',
        category: 'Infusiones',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'ROEN',
        newStock: '',
        jared: '',
      },
      {
        id: '83',
        name: 'SABROSEADOR COMPLETO',
        cost: '6.14285714',
        price1000: '8.60',
        price100: '0.92',
        price50: '0.52',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '245',
        newStock: '',
        jared: '',
      },
      {
        id: '84',
        name: 'SAL ROSADA',
        cost: '5.9',
        price1000: '8.26',
        price100: '0.89',
        price50: '0.50',
        unit: 'g',
        type: '',
        category: 'Condimentos',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '123',
        name: 'SEMILLAS DE AUYAMA CON CAS',
        cost: '12',
        price1000: '19.00',
        price100: '2.00',
        price50: '1.10',
        unit: 'g',
        type: null,
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '444',
        newStock: '',
        jared: '',
      },
      {
        id: '101',
        name: 'SEN EN HOJAS',
        cost: '7.40458195',
        price1000: '10.37',
        price100: '1.11',
        price50: '0.63',
        unit: 'g',
        type: null,
        category: 'Infusiones',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'SEN1',
        newStock: '',
        jared: '',
      },
      {
        id: '45',
        name: 'SESAMO',
        cost: '11.2866077',
        price1000: '15.80',
        price100: '1.69',
        price50: '0.96',
        unit: 'g',
        type: '',
        category: 'Cereales',
        stock: '5000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '541',
        newStock: '',
        jared: '',
      },
      {
        id: '36',
        name: 'TE NEGRO EN HOJAS',
        cost: '21.1467991',
        price1000: '29.61',
        price100: '3.17',
        price50: '1.80',
        unit: 'g',
        type: '',
        category: 'Infusiones',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'TENEGRO',
        newStock: '',
        jared: '',
      },
      {
        id: '35',
        name: 'TE VERDE EN HOJAS',
        cost: '22.7656364',
        price1000: '31.87',
        price100: '3.41',
        price50: '1.94',
        unit: 'g',
        type: '',
        category: 'Infusiones',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: 'TE VERDE 2',
        newStock: '',
        jared: '',
      },
      {
        id: '34',
        name: 'TILO EN HOJAS',
        cost: '1.2',
        price1000: '39.74',
        price100: '0.18',
        price50: '0.10',
        unit: 'g',
        type: '',
        category: 'Infusiones',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: null,
        newStock: '',
        jared: '',
      },
      {
        id: '39',
        name: 'TOMILLO',
        cost: '10.71',
        price1000: '14.99',
        price100: '1.61',
        price50: '0.91',
        unit: 'g',
        type: '',
        category: 'Infusiones',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '120',
        newStock: '',
        jared: '',
      },
      {
        id: '47',
        name: 'TRIGO PICADO Nº 1',
        cost: '4.33419933',
        price1000: '6.07',
        price100: '0.65',
        price50: '0.37',
        unit: 'g',
        type: '',
        category: 'Cereales',
        stock: '5000',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '594',
        newStock: '',
        jared: '',
      },
      {
        id: '53',
        name: 'UVAS PASAS',
        cost: '5.36904761',
        price1000: '9.00',
        price100: '0.95',
        price50: '0.50',
        unit: 'g',
        type: '',
        category: 'Otros',
        stock: '0',
        can_jar: '1',
        status: '1',
        has_details: '0',
        description: null,
        web: '1',
        external_id: '047',
        newStock: '',
        jared: '',
      },
    ],
  },
}).$start();
